# Site wide configuration

title: Cizixs Writes Here
locale: en_US
description: Tech, Python, Reading, Life, And Love.
logo: site-logo.png
search: true
url: http://cizixs.com

# Jekyll configuration

permalink:   /:year/:month/:day/:title
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: cizixs
  avatar: bio-photo.jpg
  email: wuwei4455@email.com
  disqus-shortname: jack__wu
  twitter: #cizixs
  facebook: #username
  github: #cizixs
  stackexchange: #http://stackoverflow.com/users/1925083/cizixs
  linkedin: #username
  instagram: #cizixs
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #1921727853
  google:
    plus: #wei wu
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
